### ISSUE TITLE
HS105 - 'true' or 'false' does not work but 'switch' does

### ISSUE THREAD

**Issue by juggledad** [mental05/node-red-contrib-tplink-iot#9]
**Describe the bug**
Sending eithor 'true' or 'false to an HS105 has no effect while sending 'switch' does flip the switch on the device
**To Reproduce**
1. setup a HS105 normally
2. Install the node and let it find the device
3. Create 3 inject nodes to send 'true', 'false' and 'switch' - also tried 1/0 and 'on/off', 'ON,OFF'
4. Test all three nodes and only 'switch' will have an effect

**Expected behavior**
True and false should have an effect
**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Safari
 - Version 11.1.2
 - tp-link software - tested on two devices
       device 1: 1.1.4 Build 170221 Rel.085223
       device 2: 1.5.1 Build 171109 Rel.165500

**Additional context**
I am able to control the device using https://github.com/softScheck/tplink-smartplug via an exec node

**Comment by juggledad** [comment]
Ok, I discovered what the issue is. It is looking or a BOOLEAN TRUE/FALSE while I was sending the string true/false.

To fix this I added some code to smart-plug.js which will first check msg.payload to see if it is a string, then set the value to uppercase and test for TRUE/ON or FALSE/OFF and then set msg.payload to boolean true/false based on the result

                    if (typeof msg.payload === 'string' || msg.payload instanceof String) {
				var msg_test = msg.payload.toUpperCase();
	                        if(msg_test == 'TRUE'||msg_test == 'ON') {msg.payload = true;}
				if(msg_test == 'FALSE'||msg_test == 'OFF') {msg.payload = false;}
			}

I think this would be a good addition to help others out in the future. If you agree, I'll do a PR.

**Comment by mental05** [comment]
Thank you so much for the help. I don't own a plug and I was waiting for others to see the issues.
Sure, make the request and let's get it working. I will release it again in a few hours.

**Comment by juggledad** [comment]
PR complete - I did just add it to the smart-plug.bak.js though

**Comment by juggledad** [comment]
I should have updated the readme also and changed

On/Off
true - Turn on the device.
false - Turn off the device.
switch - Toggle opposite power state of the device.

to:
On/Off
true/on - You can pass a boolean true or the string 'true or 'on' to turn on the device.
false/off - You can pass a boolean false or the string 'false' or 'off' to turn off the device.
switch - Toggle opposite power state of the device.
